---
version: '3'

services:
  chatterbox:
    image: johncapobianco/chatterbox:chatterbox
    container_name: chatterbox
    restart: always     
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8585:8585"
    volumes:
      - ./config.toml:/root/.streamlit/config.toml